version: '2'

services:
  blog.vuejs-br.com.br:
      image: jekyll/jekyll:pages
      container_name: blog.vuejs-br.com.br
      command: jekyll serve --livereload
      ports:
          - 4000:4000
          - 35729:35729
      volumes:
          - .:/srv/jekyll